# Generated by Django 5.2.6 on 2025-09-11 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อระดับชั้น')),
            ],
            options={
                'verbose_name': 'ระดับชั้น',
                'verbose_name_plural': 'ระดับชั้น',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อกลุ่มสาระการเรียนรู้')),
            ],
            options={
                'verbose_name': 'กลุ่มสาระการเรียนรู้',
                'verbose_name_plural': 'กลุ่มสาระการเรียนรู้',
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='ครูผู้สอน')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.gradelevel', verbose_name='ระดับชั้น')),
            ],
            options={
                'verbose_name': 'รายวิชาของครู',
                'verbose_name_plural': 'รายวิชาของครู',
                'ordering': ['teacher', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, verbose_name='ชื่อหน่วยการเรียนรู้')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.course', verbose_name='รายวิชา')),
            ],
            options={
                'verbose_name': 'หน่วยการเรียนรู้',
                'verbose_name_plural': 'หน่วยการเรียนรู้',
                'ordering': ['course', 'unit_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='ชื่อรายวิชา (แม่แบบ)')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_templates', to='core.learningarea', verbose_name='กลุ่มสาระการเรียนรู้')),
            ],
            options={
                'verbose_name': 'แม่แบบรายวิชา',
                'verbose_name_plural': 'แม่แบบรายวิชา',
                'ordering': ['learning_area', 'subject_name'],
                'unique_together': {('subject_name', 'learning_area')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.subjecttemplate', verbose_name='รายวิชา (จากแม่แบบ)'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'teacher')},
        ),
    ]
