# Generated by Django 5.2.6 on 2025-09-11 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='สังกัด/โรงเรียน')),
                ('learning_area', models.CharField(max_length=100, verbose_name='กลุ่มสาระการเรียนรู้')),
                ('teaching_level', models.CharField(max_length=50, verbose_name='ระดับการสอน')),
                ('teaching_experience', models.CharField(max_length=20, verbose_name='ประสบการณ์การสอน (ปี)')),
                ('usage_duration', models.CharField(max_length=20, verbose_name='ระยะเวลาใช้งานระบบ')),
                ('suggestion_likes', models.TextField(blank=True, null=True, verbose_name='สิ่งที่ชื่นชอบมากที่สุด')),
                ('suggestion_improvements', models.TextField(blank=True, null=True, verbose_name='สิ่งที่ต้องการให้ปรับปรุง')),
                ('suggestion_future', models.TextField(blank=True, null=True, verbose_name='ข้อเสนอแนะอื่นๆ')),
                ('is_locked', models.BooleanField(default=True, verbose_name='สถานะการล็อก')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=10, verbose_name='รหัสคำถามประเมิน')),
                ('rating', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='คะแนน')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='feedback.surveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
