# Generated by Django 5.2.6 on 2025-09-11 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer')], max_length=10)),
                ('difficulty_level', models.FloatField(default=0.5, help_text='ค่าดัชนีความยาก (p-value) ระหว่าง 0.00 ถึง 1.00')),
                ('bloom_level', models.CharField(choices=[('REMEMBER', 'ความรู้ความจำ (Remembering)'), ('UNDERSTAND', 'ความเข้าใจ (Understanding)'), ('APPLY', 'การนำไปใช้ (Applying)'), ('ANALYZE', 'การวิเคราะห์ (Analyzing)'), ('EVALUATE', 'การประเมินค่า (Evaluating)'), ('CREATE', 'การสร้างสรรค์ (Creating)')], default='UNDERSTAND', max_length=20, verbose_name='ระดับการเรียนรู้ (Bloom)')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.learningunit')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='รายวิชา')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='exams', to='exam_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer', to='exam_management.question')),
            ],
        ),
    ]
