# Generated by Django 5.2.6 on 2025-09-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='รูปภาพประกอบ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'ประเภทปรนัย (Multiple Choice)'), ('SHORT', 'ประเภทอัตนัยสั้น (Short Answer)')], max_length=10),
        ),
    ]
